export const DB = {
  shopTypes: [
    { id: "1", name: "Restaurant", icon: "restaurant-outline" },
    { id: "2", name: "Clothes", icon: "shirt-outline" },
    { id: "3", name: "Furniture", icon: "bed-outline" },
    { id: "4", name: "Electronics", icon: "laptop-outline" },
    { id: "5", name: "Bakery", icon: "pizza-outline" },
    { id: "6", name: "Pharmacy", icon: "medkit-outline" },
    { id: "7", name: "Bookstore", icon: "book-outline" },
    { id: "8", name: "Jewelry", icon: "diamond-outline" },
    { id: "9", name: "Sports", icon: "barbell-outline" },
    { id: "10", name: "Toys", icon: "game-controller-outline" },
    { id: "11", name: "Pet Shop", icon: "paw-outline" },
    { id: "12", name: "Supermarket", icon: "cart-outline" },
    { id: "13", name: "Cafe", icon: "cafe-outline" },
    { id: "14", name: "Barber", icon: "cut-outline" },
    { id: "15", name: "Beauty Salon", icon: "sparkles-outline" },
    { id: "16", name: "Car Dealership", icon: "car-outline" },
    { id: "17", name: "Gas Station", icon: "flash-outline" },
    { id: "18", name: "Hardware", icon: "construct-outline" },
    { id: "19", name: "Flower Shop", icon: "flower-outline" },
    { id: "20", name: "Gift Shop", icon: "gift-outline" },
    { id: "21", name: "Music Store", icon: "musical-notes-outline" },
    { id: "22", name: "Shoe Store", icon: "walk-outline" },
    { id: "23", name: "Watch Shop", icon: "time-outline" },
    { id: "24", name: "Mobile Store", icon: "phone-portrait-outline" },
    { id: "25", name: "Computer Store", icon: "desktop-outline" },
    { id: "26", name: "Gaming", icon: "game-controller-outline" },
    { id: "27", name: "Stationery", icon: "pencil-outline" },
    { id: "28", name: "Travel Agency", icon: "airplane-outline" },
    { id: "29", name: "Cinema", icon: "film-outline" },
    { id: "30", name: "Theater", icon: "easel-outline" },
    { id: "31", name: "Photography", icon: "camera-outline" },
    { id: "32", name: "Printing", icon: "print-outline" },
    { id: "33", name: "Laundry", icon: "water-outline" },
    { id: "34", name: "Fast Food", icon: "fast-food-outline" },
    { id: "35", name: "Ice Cream", icon: "ice-cream-outline" },
    { id: "36", name: "Hotel", icon: "bed-outline" },
    { id: "37", name: "Clinic", icon: "medkit-outline" },
    { id: "38", name: "Dentist", icon: "medkit-outline" },
    { id: "39", name: "Gym", icon: "barbell-outline" },
    { id: "40", name: "Spa", icon: "leaf-outline" },
    { id: "41", name: "Tattoo", icon: "color-palette-outline" },
    { id: "42", name: "Repair Shop", icon: "hammer-outline" },
    { id: "43", name: "Cleaning", icon: "water-outline" },
    { id: "44", name: "Courier", icon: "bicycle-outline" },
    { id: "45", name: "Bike Shop", icon: "bicycle-outline" },
    { id: "46", name: "Optics", icon: "eye-outline" },
    { id: "47", name: "Garden Center", icon: "leaf-outline" },
    { id: "48", name: "Meat Shop", icon: "restaurant-outline" },
    { id: "49", name: "Seafood", icon: "fish-outline" },
    { id: "50", name: "Liquor Store", icon: "wine-outline" },
  ],
};
